teleop_twist_joy_node:
  ros__ns: /T1/R1
  ros__parameters:
    axis_linear:
      x: 4
      y: 0
    scale_linear:
      x: 0.5
      y: 0.5
    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.5
    enable_button: 5
    enable_turbo_button: 8
