FROM ubuntu:focal

RUN apt-get update && \
    apt-get install -y libbluetooth3 lftp ssh libzmq5 curl gnupg2 lsb-release wget

RUN apt-get update && \
    apt-get install -y \
    git \
    python3-pip \
    net-tools \
    nmap
